### Health Check
GET http://localhost:3030/api/health
content-type: application/json

### Test Case 1
POST http://localhost:3030/api/todos 
content-type: application/json

{
    "title": "Test Todo",
    "content": "Wed, 21 Oct 2015 18:27:50 GMT"
}

### Test Case 2
GET http://localhost:3030/api/todos
content-type: application/json

### Test Case 3 - Copy the id from above response
GET http://localhost:3030/api/todos/ba88d18c-aa99-4271-8410-bd3ed2fdf3de
content-type: application/json

### Test Case 4 - Copy the id from above response
PUT http://localhost:3030/api/todos/ba88d18c-aa99-4271-8410-bd3ed2fdf3de
content-type: application/json

{
    "title": "Test Todo Updated",
    "completed": true,
    "content": "Wed, 21 Oct 2015 18:27:50 GMT"
}